#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msr-tools
Version  : 1.3
Release  : 2
URL      : https://01.org/sites/default/files/downloads/msr-tools/msr-tools-1.3.zip
Source0  : https://01.org/sites/default/files/downloads/msr-tools/msr-tools-1.3.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: msr-tools-bin
Patch1: 0001-autospec.patch

%description
No detailed description available

%package bin
Summary: bin components for the msr-tools package.
Group: Binaries

%description bin
bin components for the msr-tools package.


%prep
%setup -q -n msr-tools-master
%patch1 -p1

%build
export LANG=C
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/cpuid
/usr/bin/rdmsr
/usr/bin/wrmsr
